name: Automated Test

on: [pull_request]

jobs:
  jest:
    name: jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          bode-version: "lts/jod"
      #executa o que está no package-lock.json
      - run: npm ci
      - run: npm run test
